"""Provider-independent AI contracts and structural provider protocols."""

from sofias_assistant.ai.contracts import (
    AIMessage,
    AIMessageRole,
    AIRequest,
    AIRequestRequirements,
    Capability,
    DataLocality,
    ExecutionLocation,
    ModelDescriptor,
    ModelIdentity,
    ProviderCompleted,
    ProviderError,
    ProviderErrorCategory,
    ProviderFailed,
    ProviderInvocationError,
    ProviderResponseMetadata,
    ProviderStreamEvent,
    StructuredOutputResult,
    StructuredOutputSpec,
    TextDelta,
    TextResponse,
    ToolCallProposal,
    ToolCallProposed,
    UsageMetadata,
    UsageUpdated,
    is_terminal_stream_event,
)
from sofias_assistant.ai.providers import (
    StructuredOutputProvider,
    TextGenerationProvider,
    TextStreamingProvider,
)

__all__ = [
    "AIMessage",
    "AIMessageRole",
    "AIRequest",
    "AIRequestRequirements",
    "Capability",
    "DataLocality",
    "ExecutionLocation",
    "ModelDescriptor",
    "ModelIdentity",
    "ProviderCompleted",
    "ProviderError",
    "ProviderErrorCategory",
    "ProviderFailed",
    "ProviderInvocationError",
    "ProviderResponseMetadata",
    "ProviderStreamEvent",
    "StructuredOutputProvider",
    "StructuredOutputResult",
    "StructuredOutputSpec",
    "TextDelta",
    "TextGenerationProvider",
    "TextResponse",
    "TextStreamingProvider",
    "ToolCallProposal",
    "ToolCallProposed",
    "UsageMetadata",
    "UsageUpdated",
    "is_terminal_stream_event",
]
